# frozen_string_literal: true

ruby File.read(File.join(__dir__, ".ruby-version")).strip

source "https://rubygems.org"

gem "zeitwerk", "~> 2.6"

gem "pastel"
gem "tty-prompt"
gem "open3"
gem "dry-cli"

