# frozen_string_literal: true

ruby '3.4.9'

ruby File.read(File.join(__dir__, '.ruby-version')).strip

source 'https://rubygems.org'

gem 'zeitwerk', '~> 2.6'

gem 'dry-cli'
gem 'open3'
gem 'pastel'
gem 'tty-prompt'
