# frozen_string_literal: true

ruby File.read(".ruby-version").strip

source "https://rubygems.org"

gem "zeitwerk", "~> 2.6"

gem "pastel"
gem "tty-box"
gem "tty-prompt"
gem "tty-screen"
gem "tty-spinner"

gem "dry-cli"

