format = "$all"

[directory]
repo_root_style = 'white bold'
repo_root_format = '[$before_root_path]($before_repo_root_style)[\[$repo_root\]]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_symbol = '[/]'
fish_style_pwd_dir_length = 2

[env_var.WORK_TYPE]
default = " <=> "
format = "[ $env_value ]($style) "
style = "bold fg:white bg:green"

[kubernetes]
disabled = false

[status]
disabled = false

[time]
disabled = false

