[tools]
ghcup = "latest"
go = "latest"
node = "latest"
ruby = "3.4.9"
rust = "latest"
stack = "latest"
zig = "latest"
zls = "latest"

[settings]
idiomatic_version_file_enable_tools = []

# Use precompiled Ruby binaries instead of building from source
[settings.ruby]
compile = false
