# greetd — minimal login/session daemon.

[terminal]
vt = 1

[default_session]
# tuigreet flags:
#   --time              show a clock
#   --remember          remember the last logged-in username
#   --remember-session  remember the last chosen session
#   --asterisks         mask the password with asterisks
#
command = "tuigreet --time --remember --asterisks --remember-session --sessions /usr/share/wayland-sessions "

# Unprivileged user the greeter UI runs as (created by the greetd package).
user = "greeter"
